### ISSUE TITLE
Cannot run `pip-compile-multi` anymore: Could not find a version that matches importlib-resources<3.5,>=3.0,>=5.4

### ISSUE THREAD

**Issue by JohanLorenzo** [taskcluster/taskgraph#137]
## Steps to reproduce

Run: 

```sh
docker run -t -v "$PWD:/src" -w /src python:3.6 bash -cx "pip install pip-compile-multi && pip-compile-multi --generate-hashes base --generate-hashes dev --generate-hashes test --allow-unsafe"
```

## Expected result

All requirements get bumped

## Actual result

Only `base.txt` does. The script fails to handle `test.txt` (which also blocks `dev.txt`). It errors out this way:

```
Finding the best candidates:
  found candidate alabaster==0.7.12 (constraint was >=0.7,<0.8)
  [...]
  found candidate importlib-metadata==4.8.3 (constraint was >=0.12,>=4.8.3)
Could not find a version that matches importlib-resources<3.5,>=3.0,>=5.4 (from sphinx-book-theme==0.2.0->-r requirements/test.in (line 11))
Tried: 0.1.0, 0.1.0, 0.2, 0.2, 0.3, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.8, 1.0, 1.0.1, 1.0.1, 1.0.2, 1.0.2, 1.1.0, 1.1.0, 1.2.0, 1.2.0, 1.3.0, 1.3.0, 1.3.1, 1.3.1, 1.4.0, 1.4.0, 1.5.0, 1.5.0, 2.0.0, 2.0.0, 2.0.1, 2.0.1, 3.0.0, 3.0.0, 3.1.0, 3.1.0, 3.1.1, 3.1.1, 3.2.0, 3.2.0, 3.2.1, 3.2.1, 3.3.0, 3.3.0, 3.3.1, 3.3.1, 4.0.0, 4.0.0, 4.1.0, 4.1.0, 4.1.1, 4.1.1, 5.0.0, 5.0.0, 5.0.2, 5.0.2, 5.0.3, 5.0.3, 5.0.4, 5.0.4, 5.0.5, 5.0.5, 5.0.6, 5.0.6, 5.0.7, 5.0.7, 5.1.0, 5.1.0, 5.1.1, 5.1.1, 5.1.2, 5.1.2, 5.1.3, 5.1.3, 5.1.4, 5.1.4, 5.2.0, 5.2.0, 5.2.1, 5.2.1, 5.2.2, 5.2.2, 5.2.3, 5.2.3, 5.3.0, 5.3.0, 5.4.0, 5.4.0
There are incompatible versions in the resolved dependencies:
  importlib-resources<3.5,>=3.0 (from sphinx-book-theme==0.2.0->-r requirements/test.in (line 11))
  importlib-resources>=5.4 (from virtualenv==20.16.5->tox==3.26.0->-r requirements/test.in (line 13))

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pipcompilemulti/cli_v1.py", line 26, in cli
    recompile()
  File "/usr/local/lib/python3.6/site-packages/pipcompilemulti/actions.py", line 31, in recompile
    compile_topologically(env_confs, deduplicator)
  File "/usr/local/lib/python3.6/site-packages/pipcompilemulti/actions.py", line 38, in compile_topologically
    if env.maybe_create_lockfile():
  File "/usr/local/lib/python3.6/site-packages/pipcompilemulti/environment.py", line 51, in maybe_create_lockfile
    self.create_lockfile()
  File "/usr/local/lib/python3.6/site-packages/pipcompilemulti/environment.py", line 80, in create_lockfile
    raise RuntimeError("Failed to pip-compile {0}".format(self.infile))
RuntimeError: Failed to pip-compile requirements/test.in
```

This is likely a regression introduced in https://github.com/taskcluster/taskgraph/pull/83. 

## Additional notes

It hasn't blocked me so far since I've been able to bump `base.txt` anyway. I just filed this ticket in order to keep a record of that bug.

**Comment by JohanLorenzo** [comment]
Should be fixed by https://github.com/taskcluster/taskgraph/pull/175

**Comment by bhearsum** [comment]
@JohanLorenzo Is this fixed?

**Comment by JohanLorenzo** [comment]
I just checked, and we're getting closer! #175 reduced the gap between the 2 versions, but we're still experiencing an incompatibility: 

```
Could not find a version that matches importlib-resources<5.3,>=5.4 (from pre-commit==2.17.0->-r requirements/dev.in (line 2))
Tried: 0.1.0, 0.1.0, 0.2, 0.2, 0.3, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.8, 1.0, 1.0.1, 1.0.1, 1.0.2, 1.0.2, 1.1.0, 1.1.0, 1.2.0, 1.2.0, 1.3.0, 1.3.0, 1.3.1, 1.3.1, 1.4.0, 1.4.0, 1.5.0, 1.5.0, 2.0.0, 2.0.0, 2.0.1, 2.0.1, 3.0.0, 3.0.0, 3.1.0, 3.1.0, 3.1.1, 3.1.1, 3.2.0, 3.2.0, 3.2.1, 3.2.1, 3.3.0, 3.3.0, 3.3.1, 3.3.1, 4.0.0, 4.0.0, 4.1.0, 4.1.0, 4.1.1, 4.1.1, 5.0.0, 5.0.0, 5.0.2, 5.0.2, 5.0.3, 5.0.3, 5.0.4, 5.0.4, 5.0.5, 5.0.5, 5.0.6, 5.0.6, 5.0.7, 5.0.7, 5.1.0, 5.1.0, 5.1.1, 5.1.1, 5.1.2, 5.1.2, 5.1.3, 5.1.3, 5.1.4, 5.1.4, 5.2.0, 5.2.0, 5.2.1, 5.2.1, 5.2.2, 5.2.2, 5.2.3, 5.2.3, 5.3.0, 5.3.0, 5.4.0, 5.4.0
There are incompatible versions in the resolved dependencies:
  importlib-resources>=5.4 (from virtualenv==20.17.1->tox==3.28.0->-r requirements/test.in (line 7))
  importlib-resources<5.3 (from pre-commit==2.17.0->-r requirements/dev.in (line 2))
```

**Comment by ahal** [comment]
IIRC, this may be blocked on us dropping Python 3.6 support. Does it work using 3.7? I think we're close enough to dropping 3.6 in Gecko that we should just make it official here if this is causing problems.

**Comment by ahal** [comment]
We've dropped 3.6 support and I believe this should no longer be an issue.
