### ISSUE TITLE
Provide a better error message when invalid dependencies are specified

### ISSUE THREAD

**Issue by ahal** [taskcluster/taskgraph#228]
Over in https://github.com/mozilla-mobile/firefox-android/pull/1578 I was helping @rahulsainani out with a Taskgraph problem. Turns out it was just an invalid dependency being listed, but the error Taskgraph spits out is terrible:
```
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.10/site-packages/taskgraph/main.py", line 828, in main
    args.command(vars(args))
  File "/opt/homebrew/lib/python3.10/site-packages/taskgraph/main.py", line 411, in show_taskgraph
    generate_taskgraph(options, parameters, logdir)
  File "/opt/homebrew/lib/python3.10/site-packages/taskgraph/main.py", line 190, in generate_taskgraph
    out = format_taskgraph(options, spec, logfile(spec))
  File "/opt/homebrew/lib/python3.10/site-packages/taskgraph/main.py", line 146, in format_taskgraph
    tg = getattr(tgg, options["graph_attr"])
  File "/opt/homebrew/lib/python3.10/site-packages/taskgraph/generator.py", line 168, in full_task_graph
    return self._run_until("full_task_graph")
  File "/opt/homebrew/lib/python3.10/site-packages/taskgraph/generator.py", line 422, in _run_until
    k, v = next(self._run)
  File "/opt/homebrew/lib/python3.10/site-packages/taskgraph/generator.py", line 335, in _run
    yield self.verify("full_task_graph", full_task_graph, graph_config, parameters)
  File "/opt/homebrew/lib/python3.10/site-packages/taskgraph/generator.py", line 429, in verify
    verifications(name, obj, *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/taskgraph/util/verify.py", line 104, in __call__
    verification.verify(*args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/taskgraph/util/verify.py", line 53, in verify
    graph.for_each_task(
  File "/opt/homebrew/lib/python3.10/site-packages/taskgraph/taskgraph.py", line 32, in for_each_task
    task = self.tasks[task_label]
KeyError: 'generate-baseline-profiles'
```

We should provide a much nicer error that makes it clear which task has the problem, and provides a hint on how to fix it. I guess one tricky thing here is that we can't make this a verification as we need to iterate through the graph in order to run the verifications in the first place!

So possibly this will need to go directly in `generator.py` itself.

**Comment by Aakash017** [comment]
I would like to work on this

**Comment by ahal** [comment]
Hello @Aakash017 , thanks for your interest!

I think the first step here is to reproduce the issue. Please [follow the contribution docs](https://taskcluster-taskgraph.readthedocs.io/en/latest/contributing.html#clone-the-repo) to get setup, then make sure you can e.g run `taskgraph full` in this project. Next, read up on [dependencies](https://taskcluster-taskgraph.readthedocs.io/en/latest/concepts/task-graphs.html#dependencies) and see if you can edit one of the existing tasks to have an invalid dependency. Then re-run `taskgraph full` and hopefully you can manage to reproduce the error above!

At this point, if you need help being directed towards a solution, please reach out!
Thanks!

**Comment by Aakash017** [comment]
Hi @ahal I am able to setup this code and `taskgraph full` is running fine, I had gone through [dependencies](https://taskcluster-taskgraph.readthedocs.io/en/latest/concepts/task-graphs.html#dependencies) also but not able to find any existing tasks to which i can edit dependency and check. can you please help me to find ?

**Comment by ahal** [comment]
Sure thing, they're almost always in a file called `taskcluster/ci/<kind name>/kind.yml`. So for example, in this repo, here's a task that will generate the docs:
https://github.com/taskcluster/taskgraph/blob/main/taskcluster/ci/doc/kind.yml#L27

Try adding a `dependencies` key there (like the example in the docs).

**Comment by Aakash017** [comment]
```
(venv) aakashsharma@PPIN-LPT-2022-042 taskgraph % taskgraph full
2023-04-19 23:53:40,390 - INFO - Loading graph configuration.
2023-04-19 23:53:40,442 - INFO - Using Parameters(id=8132b1b2ebfe) (from defaults)
2023-04-19 23:53:40,443 - INFO - Loading kinds
2023-04-19 23:53:40,457 - INFO - Generating full task set
2023-04-19 23:53:40,473 - INFO - Generated 1 tasks for kind doc
2023-04-19 23:53:40,520 - INFO - Generated 5 tasks for kind docker-image
2023-04-19 23:53:40,523 - INFO - Generated 1 tasks for kind fetch
2023-04-19 23:53:40,525 - INFO - Generated 1 tasks for kind tests
2023-04-19 23:53:40,526 - INFO - Generated 1 tasks for kind codecov
2023-04-19 23:53:40,526 - INFO - Generating full task graph
2023-04-19 23:53:40,526 - INFO - Full task graph contains 9 tasks and 8 dependencies
Traceback (most recent call last):
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/main.py", line 828, in main
    args.command(vars(args))
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/main.py", line 411, in show_taskgraph
    generate_taskgraph(options, parameters, logdir)
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/main.py", line 190, in generate_taskgraph
    out = format_taskgraph(options, spec, logfile(spec))
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/main.py", line 146, in format_taskgraph
    tg = getattr(tgg, options["graph_attr"])
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/generator.py", line 171, in full_task_graph
    return self._run_until("full_task_graph")
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/generator.py", line 419, in _run_until
    k, v = next(self._run)
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/generator.py", line 338, in _run
    yield self.verify("full_task_graph", full_task_graph, graph_config, parameters)
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/generator.py", line 426, in verify
    verifications(name, obj, *args, **kwargs)
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/util/verify.py", line 104, in __call__
    verification.verify(*args, **kwargs)
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/util/verify.py", line 57, in verify
    parameters=parameters,
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/taskgraph.py", line 32, in for_each_task
    task = self.tasks[task_label]
KeyError: 'build-linux'

```

able to reproduce the issue

**Comment by ahal** [comment]
Great! So I think the better error handling should go somewhere around here:
https://github.com/taskcluster/taskgraph/blob/main/src/taskgraph/generator.py#L329

I'll let you play around with it. Feel free to push a PR (can be draft if it isn't ready), and we can go from there.

**Comment by Aakash017** [comment]
```
**edges without changes in dependency**
{('codecov-upload', 'build-docker-image-python', 'docker-image'),
 ('codecov-upload', 'fetch-codecov-uploader', 'fetch-codecov-uploader'),
 ('build-docker-image-decision-mobile', 'build-docker-image-decision', 'parent'),
 ('fetch-codecov-uploader', 'build-docker-image-fetch', 'docker-image'),
 ('tests-unit', 'build-docker-image-python', 'docker-image'),
 ('codecov-upload', 'tests-unit', 'tests'),
 ('doc-generate', 'build-docker-image-python', 'docker-image')}


**edges with changes in dependency**

{('tests-unit', 'build-docker-image-python', 'docker-image'),
 ('doc-generate', '**build-linux**', '**build**'),
 ('build-docker-image-decision-mobile', 'build-docker-image-decision', 'parent'),
 ('codecov-upload', 'fetch-codecov-uploader', 'fetch-codecov-uploader'),
 ('codecov-upload', 'tests-unit', 'tests'),
 ('codecov-upload', 'build-docker-image-python', 'docker-image'),
 ('fetch-codecov-uploader', 'build-docker-image-fetch', 'docker-image'),
 ('doc-generate', 'build-docker-image-python', 'docker-image')
 }
```
This is new dependency added
('doc-generate', '**build-linux**', '**build**'),

**Comment by Aakash017** [comment]
Seems like this dependency does not exist in code , so it is showing key error

**Comment by ahal** [comment]
Yes exactly :)

The issue here is that the error message is not very good. I would like to detect the error earlier (where I mentioned above) and provide a better message. Something like "Task '{label}' lists a dependency that does not exist: {dependency}". Does that make sense?

**Comment by Aakash017** [comment]
`Traceback (most recent call last):
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/main.py", line 828, in main
    args.command(vars(args))
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/main.py", line 411, in show_taskgraph
    generate_taskgraph(options, parameters, logdir)
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/main.py", line 190, in generate_taskgraph
    out = format_taskgraph(options, spec, logfile(spec))
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/main.py", line 146, in format_taskgraph
    tg = getattr(tgg, options["graph_attr"])
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/generator.py", line 171, in full_task_graph
    return self._run_until("full_task_graph")
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/generator.py", line 431, in _run_until
    k, v = next(self._run)
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/generator.py", line 338, in _run
    raise Exception(f" Task '{t.label}' lists a dependency that does not exist: '{dep}'")
Exception:  Task 'doc-generate' lists a dependency that does not exist: 'build-linux'
`

**Comment by Aakash017** [comment]
```
Traceback (most recent call last):
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/main.py", line 828, in main
    args.command(vars(args))
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/main.py", line 411, in show_taskgraph
    generate_taskgraph(options, parameters, logdir)
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/main.py", line 190, in generate_taskgraph
    out = format_taskgraph(options, spec, logfile(spec))
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/main.py", line 146, in format_taskgraph
    tg = getattr(tgg, options["graph_attr"])
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/generator.py", line 171, in full_task_graph
    return self._run_until("full_task_graph")
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/generator.py", line 431, in _run_until
    k, v = next(self._run)
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/generator.py", line 338, in _run
    raise Exception(f" Task '{t.label}' lists a dependency that does not exist: '{dep}'")
Exception:  Task 'doc-generate' lists a dependency that does not exist: 'build-linux'
```

**Comment by Aakash017** [comment]
@ahal 
Please review 
https://github.com/taskcluster/taskgraph/compare/main...Aakash017:taskgraph:main

**Comment by Aakash017** [comment]
```
Task 'doc-generate' lists a dependency that does not exist: 'build-linux'
Traceback (most recent call last):
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/main.py", line 828, in main
    args.command(vars(args))
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/main.py", line 411, in show_taskgraph
    generate_taskgraph(options, parameters, logdir)
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/main.py", line 190, in generate_taskgraph
    out = format_taskgraph(options, spec, logfile(spec))
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/main.py", line 146, in format_taskgraph
    tg = getattr(tgg, options["graph_attr"])
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/generator.py", line 171, in full_task_graph
    return self._run_until("full_task_graph")
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/generator.py", line 424, in _run_until
    k, v = next(self._run)
  File "/Users/aakashsharma/Documents/projects/taskgraph/src/taskgraph/generator.py", line 337, in _run
    raise Exception("Tasks have some dependencies that does not exist: ")
Exception: Tasks have some dependencies that does not exist:

```

@ahal for -> Refactor this so it detects all invalid dependencies for all tasks and prints every single one of them at once (this way we avoid the scenario where someone fixes one broken dependency, only to hit the next one)
pls check above if above changes are fine or not
