### ISSUE TITLE
Issue loading graph config on Community CI Decision Task

### ISSUE THREAD

**Issue by matt-boris** [taskcluster/taskgraph#30]
I ran `taskgraph full -p task-id=KMSME5jMQparn-7-8hyOdA` to test the task graph for a taskcluster release, but got this output:

```
2022-05-02 11:27:23,980 - INFO - Loading graph configuration.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/yaml/reader.py", line 156, in update
    data, converted = self.raw_decode(self.raw_buffer,
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/taskgraph/main.py", line 742, in main
    args.command(vars(args))
  File "/opt/homebrew/lib/python3.9/site-packages/taskgraph/main.py", line 409, in show_taskgraph
    generate_taskgraph(options, parameters, logdir)
  File "/opt/homebrew/lib/python3.9/site-packages/taskgraph/main.py", line 188, in generate_taskgraph
    out = format_taskgraph(options, spec, logfile(spec))
  File "/opt/homebrew/lib/python3.9/site-packages/taskgraph/main.py", line 144, in format_taskgraph
    tg = getattr(tgg, options["graph_attr"])
  File "/opt/homebrew/lib/python3.9/site-packages/taskgraph/generator.py", line 170, in full_task_graph
    return self._run_until("full_task_graph")
  File "/opt/homebrew/lib/python3.9/site-packages/taskgraph/generator.py", line 412, in _run_until
    k, v = next(self._run)
  File "/opt/homebrew/lib/python3.9/site-packages/taskgraph/generator.py", line 264, in _run
    parameters = self._parameters(graph_config)
  File "/opt/homebrew/lib/python3.9/site-packages/taskgraph/parameters.py", line 326, in get_parameters
    parameters = load_parameters_file(
  File "/opt/homebrew/lib/python3.9/site-packages/taskgraph/parameters.py", line 309, in load_parameters_file
    kwargs = yaml.load_stream(f)
  File "/opt/homebrew/lib/python3.9/site-packages/taskgraph/util/yaml.py", line 24, in load_stream
    loader = UnicodeLoader(stream)
  File "/opt/homebrew/lib/python3.9/site-packages/yaml/loader.py", line 34, in __init__
    Reader.__init__(self, stream)
  File "/opt/homebrew/lib/python3.9/site-packages/yaml/reader.py", line 85, in __init__
    self.determine_encoding()
  File "/opt/homebrew/lib/python3.9/site-packages/yaml/reader.py", line 135, in determine_encoding
    self.update(1)
  File "/opt/homebrew/lib/python3.9/site-packages/yaml/reader.py", line 164, in update
    raise ReaderError(self.name, position, character,
yaml.reader.ReaderError: unacceptable character #x008b: invalid start byte
  in "<file>", position 1
  ```

I made sure to `export TASKCLUSTER_ROOT_URL=https://community-tc.services.mozilla.com` as well before running. (Received 404s before setting the root url - likely due to `taskgraph` defaulting to FxCI root)

**Comment by ahal** [comment]
So it looks like this might actually be an issue with the Community instance. It appears that the content-encoding of the artifacts is set incorrectly or something. Here's a simple test case:

```
$ curl https://firefoxci.taskcluster-artifacts.net/c-tvxuhTQW6chOk6YVvX9g/0/public/parameters.yml
base_repository: https://github.com/mozilla-mobile/mozilla-vpn-client
build_date: 1651599842
...

$ curl https://community.taskcluster-artifacts.net/DHKH6felTwybWc0zRTVvIA/0/public/parameters.yml
Warning: Binary output can mess up your terminal. Use "--output -" to tell
Warning: curl to output it to your terminal anyway, or consider "--output
Warning: <FILE>" to save to a file.
```

I'm not sure where the encoding of these artifacts would get set though...

**Comment by ahal** [comment]
Ah, I guess they're just gzipped.. that seems fixable in Taskgraph
