### ISSUE TITLE
Exception running `taskgraph load-task`: TypeError: request() got an unexpected keyword argument 'chunked'

### ISSUE THREAD

**Issue by ahal** [taskcluster/taskgraph#329]
STR:
```
$ taskgraph load-image --task-id=$TASK_ID
Traceback (most recent call last):
  File "/home/ahal/dev/taskgraph/src/taskgraph/main.py", line 558, in load_image
    ok = load_image_by_task_id(args["task_id"], args.get("tag"))
  File "/home/ahal/dev/taskgraph/src/taskgraph/docker.py", line 64, in load_image_by_task_id
    result = load_image(artifact_url, tag)
  File "/home/ahal/dev/taskgraph/src/taskgraph/docker.py", line 208, in load_image
    docker.post_to_docker(download_and_modify_image(), "/images/load", quiet=0)
  File "/home/ahal/dev/taskgraph/src/taskgraph/util/docker.py", line 50, in post_to_docker
    headers={"Content-Type": "application/x-tar"},
  File "/home/ahal/.pyenv/versions/taskgraph_37/lib/python3.7/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
  File "/home/ahal/.pyenv/versions/taskgraph_37/lib/python3.7/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ahal/.pyenv/versions/taskgraph_37/lib/python3.7/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/ahal/.pyenv/versions/taskgraph_37/lib/python3.7/site-packages/requests/adapters.py", line 497, in send
    chunked=chunked,
  File "/home/ahal/.pyenv/versions/taskgraph_37/lib/python3.7/site-packages/urllib3/connectionpool.py", line 802, in urlopen
    **response_kw,
  File "/home/ahal/.pyenv/versions/taskgraph_37/lib/python3.7/site-packages/urllib3/connectionpool.py", line 504, in _make_request
    enforce_content_length=enforce_content_length,
TypeError: request() got an unexpected keyword argument 'chunked'
```

The error is happening here:
https://github.com/ahal/taskgraph/blob/dbf7a5b75e6b81c0083eb406130eb5e384555916/src/taskgraph/util/docker.py#L45

This seems to be a common problem caused by a combination of `urllib3` releasing 2.0, Docker's http adapters and this `requests` change released in 2.29.0:
https://github.com/psf/requests/pull/6226/files

More information found here:
https://github.com/docker/docker-py/issues/3113

Practically, I think our options are to either:
1. Pin requests to < 2.29.0
2. Stop using the Docker http adapters, by either
    a. Use `docker-py` which fixed this as of 6.1.1 (would add a new dependency)
    b, Shell out to `docker` cli (untested, may not work)

**Comment by bhearsum** [comment]
Maybe I'm misunderstanding the problem, but shelling out seems like a fairly safe bet. AFAICT we're just streaming a tar file to the API, and `docker load` can do that itself with `-i`.
