### ISSUE TITLE
Print a nice error message when using `taskgraph {load|build}-image` without docker started

### ISSUE THREAD

**Issue by ahal** [taskcluster/taskgraph#43]
Currently you get the following very confusing output:
```
$ taskgraph load-image --task-id=ROzeMiL1Rv-5A_uIhJr4UA
Traceback (most recent call last):
  File "/home/ahal/.pyenv/versions/taskgraph/lib/python3.7/site-packages/requests/adapters.py", line 470, in send
    low_conn.endheaders()
  File "/home/ahal/.pyenv/versions/3.7.12/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/ahal/.pyenv/versions/3.7.12/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/home/ahal/.pyenv/versions/3.7.12/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/home/ahal/.pyenv/versions/taskgraph/lib/python3.7/site-packages/requests_unixsocket/adapters.py", line 41, in connect
    sock.connect(socket_path)
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ahal/dev/taskgraph/src/taskgraph/main.py", line 544, in load_image
    ok = load_image_by_task_id(args["task_id"], args.get("tag"))
  File "/home/ahal/dev/taskgraph/src/taskgraph/docker.py", line 61, in load_image_by_task_id
    result = load_image(artifact_url, tag)
  File "/home/ahal/dev/taskgraph/src/taskgraph/docker.py", line 198, in load_image
    docker.post_to_docker(download_and_modify_image(), "/images/load", quiet=0)
  File "/home/ahal/dev/taskgraph/src/taskgraph/util/docker.py", line 49, in post_to_docker
    headers={"Content-Type": "application/x-tar"},
  File "/home/ahal/.pyenv/versions/taskgraph/lib/python3.7/site-packages/requests/sessions.py", line 577, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/home/ahal/.pyenv/versions/taskgraph/lib/python3.7/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ahal/.pyenv/versions/taskgraph/lib/python3.7/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/ahal/.pyenv/versions/taskgraph/lib/python3.7/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: [Errno 2] No such file or directory
```

**Comment by akentominas** [comment]
Hello  @ahal !
I am newbie to open source contributions and i would like to take this assessment, if this is still valid.
From other bigginer issues discussions, i found that you recomended start from [follow the contribution docs](https://taskcluster-taskgraph.readthedocs.io/en/latest/contributing.html#clone-the-repo) so i guess this is where i need to start from.

**Comment by ahal** [comment]
Hi @akentominas , thanks for your interest!

Yes the first step is to get the repo cloned, and then try to reproduce the failure. This one will require some very basic knowledge of Docker (basically just that it's installed, and you are able to start/stop it on your system).

Basically run the command `taskgraph build-image fetch`. With Docker stopped, you should see an error similar to above. With Docker started, it should complete successfully. Your task will be to turn the error above into a nice message along the lines of `Error: Cannot connect to the Docker daemon. Is the docker daemon running?`

Thanks again and please reach out if you need a hand!

**Comment by JohanLorenzo** [comment]
Fixed by https://github.com/taskcluster/taskgraph/pull/237
